"""feat: add is_deleted to multiple models for soft delete

Revision ID: 12fdc547ba89
Revises: 40ec3c0e80fb
Create Date: 2026-10-01 10:26:18.705371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fdc547ba89'
down_revision: Union[str, Sequence[str], None] = '40ec3c0e80fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('maintenance_requests', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('materials_tools_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('mess_materials_tools_items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('notices', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_deleted')
    op.drop_column('notices', 'is_deleted')
    op.drop_column('mess_materials_tools_items', 'is_deleted')
    op.drop_column('materials_tools_items', 'is_deleted')
    op.drop_column('maintenance_requests', 'is_deleted')
    op.drop_column('departments', 'is_deleted')
    op.drop_column('complaints', 'is_deleted')
    # ### end Alembic commands ###
