"""feat: add is_deleted to multiple models for soft delete

Revision ID: 40ec3c0e80fb
Revises: 781b7ab0bea0
Create Date: 2026-10-01 10:24:10.051724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ec3c0e80fb'
down_revision: Union[str, Sequence[str], None] = '781b7ab0bea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_transactions_id'), table_name='materials_transactions')
    op.drop_table('materials_transactions')
    op.drop_index(op.f('ix_materials_assignments_id'), table_name='materials_assignments')
    op.drop_table('materials_assignments')
    op.create_index(op.f('ix_mess_restock_logs_id'), 'mess_restock_logs', ['id'], unique=False)
    op.drop_constraint(op.f('mess_restock_logs_item_id_fkey'), 'mess_restock_logs', type_='foreignkey')
    op.create_foreign_key(None, 'mess_restock_logs', 'mess_materials_tools_items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'mess_restock_logs', type_='foreignkey')
    op.create_foreign_key(op.f('mess_restock_logs_item_id_fkey'), 'mess_restock_logs', 'mess_materials_tools_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mess_restock_logs_id'), table_name='mess_restock_logs')
    op.create_table('materials_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('returned_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('materials_assignments_pkey'))
    )
    op.create_index(op.f('ix_materials_assignments_id'), 'materials_assignments', ['id'], unique=False)
    op.create_table('materials_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logged_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('materials_transactions_pkey'))
    )
    op.create_index(op.f('ix_materials_transactions_id'), 'materials_transactions', ['id'], unique=False)
    # ### end Alembic commands ###
